esphome:
  name: "livingcolors"
  friendly_name: livingcolors
  libraries:
    - "Wire"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TODO"

ota:
  platform: esphome
  password: "TODO"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TODO"
    password: "TODO"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/hiteule/esp-livingcolors
      ref: master
    components: [ livingcolors ]

livingcolors:
  name: "LivingColors"

light: